spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.14:3306/RezenTest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: lc
    password: lc@123456
#mybatis:
#  type-aliases-package: com.example.demo.domain
#  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.domain
